# coding: utf-8

"""
    Groupon Connect APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 3pip@groupon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mobidy_groupon_api
from mobidy_groupon_api.models.all_ofinline_response2001_bookings_items import AllOfinlineResponse2001BookingsItems  # noqa: E501
from mobidy_groupon_api.rest import ApiException


class TestAllOfinlineResponse2001BookingsItems(unittest.TestCase):
    """AllOfinlineResponse2001BookingsItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfinlineResponse2001BookingsItems(self):
        """Test AllOfinlineResponse2001BookingsItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mobidy_groupon_api.models.all_ofinline_response2001_bookings_items.AllOfinlineResponse2001BookingsItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
