# coding: utf-8

"""
    Groupon Connect APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 3pip@groupon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mobidy_groupon_api
from mobidy_groupon_api.models.inline_response20015_images import InlineResponse20015Images  # noqa: E501
from mobidy_groupon_api.rest import ApiException


class TestInlineResponse20015Images(unittest.TestCase):
    """InlineResponse20015Images unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20015Images(self):
        """Test InlineResponse20015Images"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mobidy_groupon_api.models.inline_response20015_images.InlineResponse20015Images()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
