# coding: utf-8

"""
    Groupon Connect APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 3pip@groupon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mobidy_groupon_api
from mobidy_groupon_api.api.ingestion_feed_v2_api import IngestionFeedV2Api  # noqa: E501
from mobidy_groupon_api.rest import ApiException


class TestIngestionFeedV2Api(unittest.TestCase):
    """IngestionFeedV2Api unit test stubs"""

    def setUp(self):
        self.api = IngestionFeedV2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_availability_v2(self):
        """Test case for get_availability_v2

        Availability_v2  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
