# coding: utf-8

"""
    Groupon Connect APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 3pip@groupon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mobidy_groupon_api
from mobidy_groupon_api.models.inline_response4007_units import InlineResponse4007Units  # noqa: E501
from mobidy_groupon_api.rest import ApiException


class TestInlineResponse4007Units(unittest.TestCase):
    """InlineResponse4007Units unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4007Units(self):
        """Test InlineResponse4007Units"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mobidy_groupon_api.models.inline_response4007_units.InlineResponse4007Units()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
