# coding: utf-8

"""
    Groupon Connect APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 3pip@groupon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mobidy_groupon_api
from mobidy_groupon_api.models.inline_response20018_availability import InlineResponse20018Availability  # noqa: E501
from mobidy_groupon_api.rest import ApiException


class TestInlineResponse20018Availability(unittest.TestCase):
    """InlineResponse20018Availability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20018Availability(self):
        """Test InlineResponse20018Availability"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mobidy_groupon_api.models.inline_response20018_availability.InlineResponse20018Availability()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
