# coding: utf-8

"""
    Groupon Connect APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 3pip@groupon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20018PricingDiscountedPrice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'minor_unit_amount': 'int'
    }

    attribute_map = {
        'minor_unit_amount': 'minorUnitAmount'
    }

    def __init__(self, minor_unit_amount=None):  # noqa: E501
        """InlineResponse20018PricingDiscountedPrice - a model defined in Swagger"""  # noqa: E501
        self._minor_unit_amount = None
        self.discriminator = None
        self.minor_unit_amount = minor_unit_amount

    @property
    def minor_unit_amount(self):
        """Gets the minor_unit_amount of this InlineResponse20018PricingDiscountedPrice.  # noqa: E501

        Numeric amount that is an integer in the currency’s minor unit representing the original price. For example, in USD, $10.95 would be represented as 1095.   # noqa: E501

        :return: The minor_unit_amount of this InlineResponse20018PricingDiscountedPrice.  # noqa: E501
        :rtype: int
        """
        return self._minor_unit_amount

    @minor_unit_amount.setter
    def minor_unit_amount(self, minor_unit_amount):
        """Sets the minor_unit_amount of this InlineResponse20018PricingDiscountedPrice.

        Numeric amount that is an integer in the currency’s minor unit representing the original price. For example, in USD, $10.95 would be represented as 1095.   # noqa: E501

        :param minor_unit_amount: The minor_unit_amount of this InlineResponse20018PricingDiscountedPrice.  # noqa: E501
        :type: int
        """
        if minor_unit_amount is None:
            raise ValueError("Invalid value for `minor_unit_amount`, must not be `None`")  # noqa: E501

        self._minor_unit_amount = minor_unit_amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20018PricingDiscountedPrice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20018PricingDiscountedPrice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
