# coding: utf-8

"""
    Groupon Connect APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 3pip@groupon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse4007Errors(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'units': 'list[InlineResponse4007Units]'
    }

    attribute_map = {
        'code': 'code',
        'units': 'units'
    }

    def __init__(self, code=None, units=None):  # noqa: E501
        """InlineResponse4007Errors - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._units = None
        self.discriminator = None
        self.code = code
        self.units = units

    @property
    def code(self):
        """Gets the code of this InlineResponse4007Errors.  # noqa: E501

        The code for this error.  # noqa: E501

        :return: The code of this InlineResponse4007Errors.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this InlineResponse4007Errors.

        The code for this error.  # noqa: E501

        :param code: The code of this InlineResponse4007Errors.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501
        allowed_values = ["RESERVATION_NOT_FOUND", "MALFORMED_REQUEST", "RESERVATION_NOT_CANCELLABLE"]  # noqa: E501
        if code not in allowed_values:
            raise ValueError(
                "Invalid value for `code` ({0}), must be one of {1}"  # noqa: E501
                .format(code, allowed_values)
            )

        self._code = code

    @property
    def units(self):
        """Gets the units of this InlineResponse4007Errors.  # noqa: E501

        An array of units associated with this error.  # noqa: E501

        :return: The units of this InlineResponse4007Errors.  # noqa: E501
        :rtype: list[InlineResponse4007Units]
        """
        return self._units

    @units.setter
    def units(self, units):
        """Sets the units of this InlineResponse4007Errors.

        An array of units associated with this error.  # noqa: E501

        :param units: The units of this InlineResponse4007Errors.  # noqa: E501
        :type: list[InlineResponse4007Units]
        """
        if units is None:
            raise ValueError("Invalid value for `units`, must not be `None`")  # noqa: E501

        self._units = units

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse4007Errors, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse4007Errors):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
