# coding: utf-8

"""
    Groupon Connect APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 3pip@groupon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse4XX1Bookings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'groupon_booking_id': 'str'
    }

    attribute_map = {
        'groupon_booking_id': 'grouponBookingId'
    }

    def __init__(self, groupon_booking_id=None):  # noqa: E501
        """InlineResponse4XX1Bookings - a model defined in Swagger"""  # noqa: E501
        self._groupon_booking_id = None
        self.discriminator = None
        self.groupon_booking_id = groupon_booking_id

    @property
    def groupon_booking_id(self):
        """Gets the groupon_booking_id of this InlineResponse4XX1Bookings.  # noqa: E501

        The Groupon booking id.  # noqa: E501

        :return: The groupon_booking_id of this InlineResponse4XX1Bookings.  # noqa: E501
        :rtype: str
        """
        return self._groupon_booking_id

    @groupon_booking_id.setter
    def groupon_booking_id(self, groupon_booking_id):
        """Sets the groupon_booking_id of this InlineResponse4XX1Bookings.

        The Groupon booking id.  # noqa: E501

        :param groupon_booking_id: The groupon_booking_id of this InlineResponse4XX1Bookings.  # noqa: E501
        :type: str
        """
        if groupon_booking_id is None:
            raise ValueError("Invalid value for `groupon_booking_id`, must not be `None`")  # noqa: E501

        self._groupon_booking_id = groupon_booking_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse4XX1Bookings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse4XX1Bookings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
