# coding: utf-8

"""
    Groupon Connect APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 3pip@groupon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20019(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'merchants': 'list[InlineResponse20019Merchants]',
        'errors': 'list[InlineResponse20019Errors]'
    }

    attribute_map = {
        'merchants': 'merchants',
        'errors': 'errors'
    }

    def __init__(self, merchants=None, errors=None):  # noqa: E501
        """InlineResponse20019 - a model defined in Swagger"""  # noqa: E501
        self._merchants = None
        self._errors = None
        self.discriminator = None
        self.merchants = merchants
        if errors is not None:
            self.errors = errors

    @property
    def merchants(self):
        """Gets the merchants of this InlineResponse20019.  # noqa: E501

        The list of merchants.  # noqa: E501

        :return: The merchants of this InlineResponse20019.  # noqa: E501
        :rtype: list[InlineResponse20019Merchants]
        """
        return self._merchants

    @merchants.setter
    def merchants(self, merchants):
        """Sets the merchants of this InlineResponse20019.

        The list of merchants.  # noqa: E501

        :param merchants: The merchants of this InlineResponse20019.  # noqa: E501
        :type: list[InlineResponse20019Merchants]
        """
        if merchants is None:
            raise ValueError("Invalid value for `merchants`, must not be `None`")  # noqa: E501

        self._merchants = merchants

    @property
    def errors(self):
        """Gets the errors of this InlineResponse20019.  # noqa: E501

        An array of errors with this request.  # noqa: E501

        :return: The errors of this InlineResponse20019.  # noqa: E501
        :rtype: list[InlineResponse20019Errors]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this InlineResponse20019.

        An array of errors with this request.  # noqa: E501

        :param errors: The errors of this InlineResponse20019.  # noqa: E501
        :type: list[InlineResponse20019Errors]
        """

        self._errors = errors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20019, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20019):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
