# coding: utf-8

"""
    Groupon Connect APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: 3pip@groupon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20011DataPriceSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency_code': 'str',
        'price': 'AllOfinlineResponse20011DataPriceSummaryPrice',
        'base_price': 'AllOfinlineResponse20011DataPriceSummaryBasePrice',
        'value': 'AllOfinlineResponse20011DataPriceSummaryValue',
        'adjustments': 'list[InlineResponse2006PriceSummaryAdjustments]'
    }

    attribute_map = {
        'currency_code': 'currencyCode',
        'price': 'price',
        'base_price': 'basePrice',
        'value': 'value',
        'adjustments': 'adjustments'
    }

    def __init__(self, currency_code=None, price=None, base_price=None, value=None, adjustments=None):  # noqa: E501
        """InlineResponse20011DataPriceSummary - a model defined in Swagger"""  # noqa: E501
        self._currency_code = None
        self._price = None
        self._base_price = None
        self._value = None
        self._adjustments = None
        self.discriminator = None
        self.currency_code = currency_code
        self.price = price
        if base_price is not None:
            self.base_price = base_price
        if value is not None:
            self.value = value
        if adjustments is not None:
            self.adjustments = adjustments

    @property
    def currency_code(self):
        """Gets the currency_code of this InlineResponse20011DataPriceSummary.  # noqa: E501

        An uppercase, three letter [ISO-4217](http://www.iso.org/iso/home/standards/currency_codes.htm) currency code.   # noqa: E501

        :return: The currency_code of this InlineResponse20011DataPriceSummary.  # noqa: E501
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code):
        """Sets the currency_code of this InlineResponse20011DataPriceSummary.

        An uppercase, three letter [ISO-4217](http://www.iso.org/iso/home/standards/currency_codes.htm) currency code.   # noqa: E501

        :param currency_code: The currency_code of this InlineResponse20011DataPriceSummary.  # noqa: E501
        :type: str
        """
        if currency_code is None:
            raise ValueError("Invalid value for `currency_code`, must not be `None`")  # noqa: E501

        self._currency_code = currency_code

    @property
    def price(self):
        """Gets the price of this InlineResponse20011DataPriceSummary.  # noqa: E501


        :return: The price of this InlineResponse20011DataPriceSummary.  # noqa: E501
        :rtype: AllOfinlineResponse20011DataPriceSummaryPrice
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this InlineResponse20011DataPriceSummary.


        :param price: The price of this InlineResponse20011DataPriceSummary.  # noqa: E501
        :type: AllOfinlineResponse20011DataPriceSummaryPrice
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def base_price(self):
        """Gets the base_price of this InlineResponse20011DataPriceSummary.  # noqa: E501


        :return: The base_price of this InlineResponse20011DataPriceSummary.  # noqa: E501
        :rtype: AllOfinlineResponse20011DataPriceSummaryBasePrice
        """
        return self._base_price

    @base_price.setter
    def base_price(self, base_price):
        """Sets the base_price of this InlineResponse20011DataPriceSummary.


        :param base_price: The base_price of this InlineResponse20011DataPriceSummary.  # noqa: E501
        :type: AllOfinlineResponse20011DataPriceSummaryBasePrice
        """

        self._base_price = base_price

    @property
    def value(self):
        """Gets the value of this InlineResponse20011DataPriceSummary.  # noqa: E501


        :return: The value of this InlineResponse20011DataPriceSummary.  # noqa: E501
        :rtype: AllOfinlineResponse20011DataPriceSummaryValue
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this InlineResponse20011DataPriceSummary.


        :param value: The value of this InlineResponse20011DataPriceSummary.  # noqa: E501
        :type: AllOfinlineResponse20011DataPriceSummaryValue
        """

        self._value = value

    @property
    def adjustments(self):
        """Gets the adjustments of this InlineResponse20011DataPriceSummary.  # noqa: E501

        Any taxes, fees to be applied on top of the price  # noqa: E501

        :return: The adjustments of this InlineResponse20011DataPriceSummary.  # noqa: E501
        :rtype: list[InlineResponse2006PriceSummaryAdjustments]
        """
        return self._adjustments

    @adjustments.setter
    def adjustments(self, adjustments):
        """Sets the adjustments of this InlineResponse20011DataPriceSummary.

        Any taxes, fees to be applied on top of the price  # noqa: E501

        :param adjustments: The adjustments of this InlineResponse20011DataPriceSummary.  # noqa: E501
        :type: list[InlineResponse2006PriceSummaryAdjustments]
        """

        self._adjustments = adjustments

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20011DataPriceSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20011DataPriceSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
